// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: doc2vec.proto

package skadi_bot_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Doc2VecService_GetDoc2Vec_FullMethodName = "/doc2vec.Doc2VecService/GetDoc2Vec"
)

// Doc2VecServiceClient is the client API for Doc2VecService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Doc2VecServiceClient interface {
	GetDoc2Vec(ctx context.Context, in *Doc2VecRequest, opts ...grpc.CallOption) (*Doc2VecResponse, error)
}

type doc2VecServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDoc2VecServiceClient(cc grpc.ClientConnInterface) Doc2VecServiceClient {
	return &doc2VecServiceClient{cc}
}

func (c *doc2VecServiceClient) GetDoc2Vec(ctx context.Context, in *Doc2VecRequest, opts ...grpc.CallOption) (*Doc2VecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Doc2VecResponse)
	err := c.cc.Invoke(ctx, Doc2VecService_GetDoc2Vec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Doc2VecServiceServer is the server API for Doc2VecService service.
// All implementations must embed UnimplementedDoc2VecServiceServer
// for forward compatibility.
type Doc2VecServiceServer interface {
	GetDoc2Vec(context.Context, *Doc2VecRequest) (*Doc2VecResponse, error)
	mustEmbedUnimplementedDoc2VecServiceServer()
}

// UnimplementedDoc2VecServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDoc2VecServiceServer struct{}

func (UnimplementedDoc2VecServiceServer) GetDoc2Vec(context.Context, *Doc2VecRequest) (*Doc2VecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDoc2Vec not implemented")
}
func (UnimplementedDoc2VecServiceServer) mustEmbedUnimplementedDoc2VecServiceServer() {}
func (UnimplementedDoc2VecServiceServer) testEmbeddedByValue()                        {}

// UnsafeDoc2VecServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Doc2VecServiceServer will
// result in compilation errors.
type UnsafeDoc2VecServiceServer interface {
	mustEmbedUnimplementedDoc2VecServiceServer()
}

func RegisterDoc2VecServiceServer(s grpc.ServiceRegistrar, srv Doc2VecServiceServer) {
	// If the following call pancis, it indicates UnimplementedDoc2VecServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Doc2VecService_ServiceDesc, srv)
}

func _Doc2VecService_GetDoc2Vec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Doc2VecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Doc2VecServiceServer).GetDoc2Vec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Doc2VecService_GetDoc2Vec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Doc2VecServiceServer).GetDoc2Vec(ctx, req.(*Doc2VecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Doc2VecService_ServiceDesc is the grpc.ServiceDesc for Doc2VecService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Doc2VecService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "doc2vec.Doc2VecService",
	HandlerType: (*Doc2VecServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDoc2Vec",
			Handler:    _Doc2VecService_GetDoc2Vec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doc2vec.proto",
}
